repositories {
    mavenCentral()
    maven {
        url = "https://maven.tealiumiq.com/android/releases/"
    }
}

dependencies {
    implementation 'com.tealium.remotecommands:firebase:1.5.0'
}

android {
    defaultConfig {
    }

    packaging {
        resources {
            excludes += ['META-INF/NOTICE', 'META-INF/LICENSE']
        }
    }
    sourceSets {
        main.java {
            srcDirs += 'src/main/kotlin'
        }
    }
}
